Repository baepo-minjok/pipely, pull requests merged in 2025-06, with the labels that each got.

#4 [Feat]: 회원 기능 구현
  backend/build.gradle
  backend/src/main/java/com/example/backend/config/AuthMangerConfig.java
  backend/src/main/java/com/example/backend/config/CorsConfig.java
  backend/src/main/java/com/example/backend/config/PasswordConfig.java
  backend/src/main/java/com/example/backend/config/SecurityConfig.java
  backend/src/main/java/com/example/backend/config/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/config/jwt/JwtTokenProvider.java
  backend/src/main/java/com/example/backend/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/example/backend/user/controller/AuthController.java
  backend/src/main/java/com/example/backend/user/model/Users.java
  backend/src/main/java/com/example/backend/user/model/VerificationToken.java
  backend/src/main/java/com/example/backend/user/model/dto/LoginRequest.java
  backend/src/main/java/com/example/backend/user/model/dto/SignupRequest.java
  backend/src/main/java/com/example/backend/user/model/dto/TokenResponse.java
  backend/src/main/java/com/example/backend/user/repository/UserRepository.java
  backend/src/main/java/com/example/backend/user/repository/VerificationTokenRepository.java
  backend/src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
  backend/src/main/java/com/example/backend/user/service/CustomUserDetailsService.java
  backend/src/main/java/com/example/backend/user/service/EmailService.java
  backend/src/main/java/com/example/backend/user/service/UserService.java
  backend/src/main/java/com/example/backend/user/service/VerificationTokenService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: enhancement

#6 [FEAT]: 전역 예외 처리
  .idea/gradle.xml
  backend/src/main/java/com/example/backend/exception/BaseResponse.java
  backend/src/main/java/com/example/backend/exception/ErrorCode.java
  backend/src/main/java/com/example/backend/exception/ErrorInfo.java
  backend/src/main/java/com/example/backend/exception/GlobalExceptionHandler.java
Labels: enhancement

#12 11 entity
  backend/src/main/java/com/example/backend/job/controller/JobController.java
  backend/src/main/java/com/example/backend/job/model/Job.java
  backend/src/main/java/com/example/backend/job/model/JobErrorLog.java
  backend/src/main/java/com/example/backend/job/model/JobErrorLogId.java
  backend/src/main/java/com/example/backend/job/model/JobSchedule.java
  backend/src/main/java/com/example/backend/job/model/JobScheduleId.java
  backend/src/main/java/com/example/backend/job/model/JobVersion.java
  backend/src/main/java/com/example/backend/job/model/JobVersionId.java
  backend/src/main/java/com/example/backend/notification/model/JobNotification.java
  backend/src/main/java/com/example/backend/notification/model/JobNotificationId.java
  backend/src/main/resources/application.yml
Labels: init

#18 [FEAT]: 젠킨스 정보 등록 구현
  backend/src/main/java/com/example/backend/exception/ErrorCode.java
  backend/src/main/java/com/example/backend/jenkins/info/controller/JenkinsInfoController.java
  backend/src/main/java/com/example/backend/jenkins/info/model/JenkinsInfo.java
  backend/src/main/java/com/example/backend/jenkins/info/model/dto/InfoRequestDto.java
  backend/src/main/java/com/example/backend/jenkins/info/repository/JenkinsInfoRepository.java
  backend/src/main/java/com/example/backend/jenkins/info/service/JenkinsInfoService.java
Labels: enhancement

#19 [DOCS]: develop 브랜치에 PR 알림 문서 추가
  .github/workflows/notify-discord-on-pr.yml
Labels: init

#26 [Feat] Jenkins 특정 job 및 전체 job 빌드 조회 기능 구현 및 응답 포맷 개선
  backend/src/main/java/com/example/backend/exception/ErrorCode.java
  backend/src/main/java/com/example/backend/jenkins/error/client/JenkinsRestClient.java
  backend/src/main/java/com/example/backend/jenkins/error/controller/ErrorController.java
  backend/src/main/java/com/example/backend/jenkins/error/model/dto/FailedBuildResDto.java
  backend/src/main/java/com/example/backend/jenkins/error/model/dto/JenkinsReqDto.java
  backend/src/main/java/com/example/backend/jenkins/error/service/ErrorService.java
Labels: backend

#46 Docs/44 deploy k8s
  backend/Dockerfile
  backend/k8s/backend-deployment.yml
  frontend/Dockerfile
  frontend/k8s/deployment/frontend-deployment.yml
  frontend/k8s/deployment/frontend-ingress.yml
  frontend/k8s/deployment/frontend-service.yml
Labels: documentation

#47 [FEAT] 회원가입 페이지, 비밀번호 찾기 & 재설정 페이지 구현
  frontend/src/assets/icons/check.svg
  frontend/src/pages/users/FindPassword.vue
  frontend/src/pages/users/Login.vue
  frontend/src/pages/users/Signup.vue
  frontend/src/router/index.js
  frontend/src/style.css
Labels: enhancement

#53 [FEAT] 메인 페이지 구현
  frontend/src/assets/icons/profile.svg
  frontend/src/assets/icons/up_arrow.svg
  frontend/src/components/common/Dropdown.vue
  frontend/src/components/common/Header.vue
  frontend/src/pages/Main.vue
  frontend/src/router/index.js
Labels: enhancement
